### ISSUE TITLE
mqtt sendEvent does not emit resolve nor reject

### ISSUE THREAD

**Issue by a8775** [Azure/azure-iot-sdk-node#754]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v10.17.0
- **npm version:** 6.11.3

# Description of the issue:
```Typescript
            let mqtt = Client.fromConnectionString(connectionStringDevice, Mqtt);
            mqtt.on('error', async (e) => {
                console.error('MQTT OnError: ', e);
            });
            mqtt.on('disconnect', async (e?: Error) => {
                console.error('MQTT OnDisconnect: ', e);
                mqtt.close();
            });
            let rp: RetryPolicy = new NoRetry();
            mqtt.setRetryPolicy(rp);
            await mqtt.open();
            let r = await mqtt.sendEvent(new Message("message: " + uuid.v4()));
            log(`sendFromDevices()...`);
```

When the daily message quota is reached, the code never get to the last line and the exception is not thrown. I get only the on('disconnect') with the following message:

```
Disconnected {transportObj: Error: Connection to the server has been closed., reason: undefined}
```
What is the intended way to recover from the last await statement? I suppose the last promise should be rejected as soon as the 'disconnect' event is emitted. May be the promise should be resolved and in the 'disconnect' event procedure I should be able to handle the problem in some way?

As soon as I increase the 'Number of IoT Hub units' the promise resolve.

**Comment by anthonyvercolano** [comment]
Would it have made a difference if you put a try around the await?

**Comment by a8775** [comment]
The isolated code to reproduce the problem (the daily limit has to be reached):

```
import * as uuid from 'uuid';
import * as itohub from 'azure-iothub';
import { RetryPolicy, NoRetry } from 'azure-iot-common';
import { Mqtt } from 'azure-iot-device-mqtt';
import { Client, Message, DeviceMethodRequest, DeviceMethodResponse } from 'azure-iot-device';

const IOT_HUB = 'XXX';
const IOT_SAK = 'XXXX';

function log(s: string) {
    console.log((new Date()).toISOString() + " - " + s);
}

async function test() {
    log('Test started...');

    let deviceId = 'test_0';

    log(`createDevices()... deviceId=${deviceId} creating mqtt...`);
    let connectionStringDevice = `HostName=${IOT_HUB}.azure-devices.net;DeviceId=${deviceId};SharedAccessKeyName=iothubowner;SharedAccessKey=${IOT_SAK}`;
    let mqtt = Client.fromConnectionString(connectionStringDevice, Mqtt);
    mqtt.on('error', async (e) => {
        console.error('MQTT OnError: ', e);
    });
    mqtt.on('disconnect', async (e?: Error) => {
        console.error('MQTT OnDisconnect: ', e);
    });
    log(`createDevices()... deviceId=${deviceId} opening mqtt...`);
    let rp: RetryPolicy = new NoRetry();
    mqtt.setRetryPolicy(rp);
    await mqtt.open();
    log(`createDevices()... deviceId=${deviceId} creating mqtt... done.`);

    // test...
    log("sendFromDevice()...");
    try {
        let r = await mqtt.sendEvent(new Message("message: " + uuid.v4()));
    }
    catch(e) {
        log(`sendFromDevice()... exception` + e);
    }
    log(`sendFromDevice()... ${deviceId}`);
}

test();
```

the output log:
```
2020-04-16T05:22:40.493Z - Test started...
2020-04-16T05:22:40.497Z - createDevices()... deviceId=test_0 creating mqtt...
2020-04-16T05:22:40.540Z - createDevices()... deviceId=test_0 opening mqtt...
2020-04-16T05:22:40.836Z - createDevices()... deviceId=test_0 creating mqtt... done.
2020-04-16T05:22:40.838Z - sendFromDevice()...
MQTT OnDisconnect:  Disconnected {
  transportObj:
   { NotConnectedError: Connection to the server has been closed. name: 'NotConnectedError' },
  reason: undefined }
```

The process is stopped. The last await was not rejected nor resolved. May I be missing something with error handling?

This is typescript the target was 'es5' but I tried with more recent versions and the output log is the same, so it's rather not a compiler problem.

**Comment by anthonyvercolano** [comment]
What also coulld have happened is that the disconnect is initialated by the server.  There is is an issure somewhat addressed by #744 that is likely what is happening here.

**Comment by a8775** [comment]
The original my problem I encountered was with throttling limitations but I'm not sure, as with many devices and many connections and random problem it was difficult to isolate. 

Because I couldn't reproduce till now I didn't create an issue about throttling but find this one

As you have said the problem possibly is with closing connection by server, that could be the case but not 100% as throttling is not supposed to close connection but I could be wrong. 

I will try to pursuit my original problem, so having a workaround would be nice.

**Comment by anthonyvercolano** [comment]
I don't actually know the rules off the top of my head about what a throttling error will do to the connection, however, there is also the possibility that the throttling *might* have caused the next attempt to re-auth the connection to fail.  With MQTT the reauth by it's very nature causes a disconnect to occur.

This merits an investigation on our part.

There is no workaround at this point, but we are actively working to fix the issue where there is not failure on the await

**Comment by a8775** [comment]
The release 1.14.0 didn't solve the problem but after reading the #770 I think this was not supposed to solve this issue yet.

**Comment by a8775** [comment]
I checked the last release 1.16.0 the problem is resolved, thank you!

**Comment by az-iot-builder-01** [comment]
@a8775, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
